// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpDN51PhOer3F-X5GvWmsgw9bmF-um4-M',
    appId: '1:76201651262:web:5b614fae96746f4ec8b56f',
    messagingSenderId: '76201651262',
    projectId: 'saglikliyasam-963d7',
    authDomain: 'saglikliyasam-963d7.firebaseapp.com',
    storageBucket: 'saglikliyasam-963d7.appspot.com',
    measurementId: 'G-Y06J46HTW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgfDxVRawemHv-BVXkW-a8e2uR2hZeCto',
    appId: '1:76201651262:android:9e15736a49449a0dc8b56f',
    messagingSenderId: '76201651262',
    projectId: 'saglikliyasam-963d7',
    storageBucket: 'saglikliyasam-963d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTouBhgFu3hAiX23Qspk5p-RcfPsS7Eno',
    appId: '1:76201651262:ios:17c6b1596bc5f55fc8b56f',
    messagingSenderId: '76201651262',
    projectId: 'saglikliyasam-963d7',
    storageBucket: 'saglikliyasam-963d7.appspot.com',
    iosClientId: '76201651262-4f21ikut7kuop8bft4l2veiduthg7a5h.apps.googleusercontent.com',
    iosBundleId: 'com.msuzgun.saglikliYasam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTouBhgFu3hAiX23Qspk5p-RcfPsS7Eno',
    appId: '1:76201651262:ios:17c6b1596bc5f55fc8b56f',
    messagingSenderId: '76201651262',
    projectId: 'saglikliyasam-963d7',
    storageBucket: 'saglikliyasam-963d7.appspot.com',
    iosClientId: '76201651262-4f21ikut7kuop8bft4l2veiduthg7a5h.apps.googleusercontent.com',
    iosBundleId: 'com.msuzgun.saglikliYasam',
  );
}
